version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: nuxt-strapi-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-strapi}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache for Development
  redis:
    image: redis:7-alpine
    container_name: nuxt-strapi-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network-dev
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  app-network-dev:
    driver: bridge
